### ISSUE TITLE
Fails on some Haswell CPUs

### ISSUE THREAD

**Issue by mateon1** [mtak-/meltdown_rust#1]
I tried running this example on my i7-4770K, but I was surprised to see that `xbeginq` was an illegal instruction.

Digging into this further seems to indicate that early Haswell CPUs had their TSX support disabled via a microcode update, due to a bug in Intel's implementation, and was only fixed in CPUs produced after November 2014.

The README for this example should be updated to reflect this.

**Comment by mtak-** [comment]
Thank you for the research. I've updated the readme.
